### ISSUE TITLE
Better document switch login details (ip, credentials)

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ansible-switches#73]
I wanted to login to the switch "MOC-R4PCC02-SW-TORS" . I grep-ed this repo for this switch and only one result showed up

https://github.com/CCI-MOC/ansible-switches/blob/ecc9f59b787cbf6d76df02bf97f0cee9b750733f/hosts#L70

but it didn't respond on the IP that's in this document. I ended up looking at the ESI config files and then logged into the switch using esi credentials  (because the credentials for the cumulus user are not in bitwarden, I found those later in my chat). These are the IPs it has:

```
esi@MOC-R4PCC02-SW-TORS:mgmt:~$ ip r
default via 10.82.0.1 dev vlan935 proto kernel
10.2.0.0/19 dev vlan911 proto kernel scope link src 10.2.19.1
10.7.0.0/20 dev vlan2304 proto kernel scope link src 10.7.0.99
10.82.0.0/20 dev vlan935 proto kernel scope link src 10.82.2.91
192.168.1.0/24 dev vlan350 proto kernel scope link src 192.168.1.3
```

I have run into this a couple of times before. We need to come up with a more reliable way of documenting these changes.

**Comment by naved001** [comment]
I do see that IP on in the config of that switch but not sure why it's down. Perhaps, it's not a documentation issue but some config issue with the switch?

```
      eth0:
        ip:
          address:
            10.80.2.91/20: {}
          gateway:
            10.80.0.1: {}
          vrf: mgmt
        type: eth
```
